// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2SdHw4xSS0zSyuy577VZ5X7GyRUO4CDM',
    appId: '1:921172015478:web:cbfcb71e72e41663cf2257',
    messagingSenderId: '921172015478',
    projectId: 'buy-it-ee713',
    authDomain: 'buy-it-ee713.firebaseapp.com',
    storageBucket: 'buy-it-ee713.appspot.com',
    measurementId: 'G-X724PNBTLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEzc_fUCgA9ZGjkqGZEXeC2wONw9U7G8E',
    appId: '1:921172015478:android:0d82d9034082df42cf2257',
    messagingSenderId: '921172015478',
    projectId: 'buy-it-ee713',
    storageBucket: 'buy-it-ee713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC0a7MbrxgA4aacHtFLsQwi7U4g3AwvKA',
    appId: '1:921172015478:ios:2e8bc1408d760462cf2257',
    messagingSenderId: '921172015478',
    projectId: 'buy-it-ee713',
    storageBucket: 'buy-it-ee713.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC0a7MbrxgA4aacHtFLsQwi7U4g3AwvKA',
    appId: '1:921172015478:ios:2e8bc1408d760462cf2257',
    messagingSenderId: '921172015478',
    projectId: 'buy-it-ee713',
    storageBucket: 'buy-it-ee713.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2SdHw4xSS0zSyuy577VZ5X7GyRUO4CDM',
    appId: '1:921172015478:web:baf3a6becb53f562cf2257',
    messagingSenderId: '921172015478',
    projectId: 'buy-it-ee713',
    authDomain: 'buy-it-ee713.firebaseapp.com',
    storageBucket: 'buy-it-ee713.appspot.com',
    measurementId: 'G-TZ9K8M2MTW',
  );
}
